[project]
name = "hello-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.18.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
    "ty>=0.0.1a23",
]
